// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlynheaudnpbbinwpppv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJseW5oZWF1ZG5wYmJpbndwcHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTUxMzIsImV4cCI6MjA2MzgzMTEzMn0.Uogv1OnmAyzovCU7JY1Ye4MWO23PCjN6R_tGlHvynV4";

// Import the supabase client like this:
//import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);